### ISSUE TITLE
Link from OS X Lattitude Forums

### ISSUE THREAD

**Issue by TheMoves** [DrHurt/OS-X-ALPS-DRIVER#1]
Can you update the link referenced in the first post? It references your old repository.
http://forum.osxlatitude.com/index.php?/topic/8285-refined-alps-touchpad-driver/

Thanks for all your work. I started using release 3 and now I don't have to get rid of my Dell 👍

**Comment by DrHurt** [comment]
I have actually started from scratch using bpedman's code as a base and _cleanly_ porting from Linux 4.7 hoping I could get a more stable driver.

The code here is not that of Release 3, but the new driver I'm working on.

Once I finish everything in a few days, I'll update the code here and make a V4 release on the forum. Hopefully Rehabman would have fixed the sierra PS2 problem by then to integrate that too.
